config/routes.rb
Rails.application.routes.draw do
 

  root      'static_pages#home'
  get 'intro' => 'static_pages#intro'
  get 'ap' => 'static_pages#ap'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/ap_seminar_controller.rb
class ApSeminarController < ApplicationController

	#layout "ap_seminar"

  def lesson_1
  end

  def lesson_2
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def hello
		render html: "hello world!"
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def intro
  end

  def ap

  
  end


  


end

app/helpers/ap_seminar_helper.rb
module ApSeminarHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "South Shore Studies"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ap_seminar/lesson_1.html.erb
<h1>ApSeminar#lesson_1</h1>
<p>Find me in app/views/ap_seminar/lesson_1.html.erb</p>

app/views/ap_seminar/lesson_2.html.erb
<h1>ApSeminar#lesson_2</h1>
<p>Find me in app/views/ap_seminar/lesson_2.html.erb</p>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "SSS", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Ap Seminar",   ap_path %></li>
            <li><%= link_to "Intro",   intro_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/ap_seminar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>South Shore Studies | <%= yield(:title) %></title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "South Shore Studies", 'static_pages/home', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Lesson 1",    'lesson_1' %></li>
              <li><%= link_to "Lesson 2",    '#' %></li>
              <li><%= link_to "Boner", '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>

    <%= render 'layouts/header' %>
   
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/ap.html.erb
<% provide(:title, "AP Seminar") %>
	<h1>AP Seminar</h1>

	<h1>Under Constuction</h1>

app/views/static_pages/ap_seminar.html.erb
<% provide(:title, "AP Seminar") %>
	<h1>AP Seminar</h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<%= image_tag("sss.png", width: 200) %>

<div class="center jumbotron">
	<h1>South Shore Studies</h1>


<h3>AP Seminar, AP Research, AP History, & AP English Tutoring</h3>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>


<%= link_to "Sign up now!", '#' , class: "btn btn lg btn-primary" %>



</div>

app/views/static_pages/intro.html.erb
<% provide(:title, "Intro") %>

	<h1>StaticPages#intro</h1>
<p>Find me in app/views/static_pages/intro.html.erb</p>